name: build-docs

on:
  push:
    branches:
      - main
      - docs-dev
    paths:
      - "docs/**"
      - "mkdocs.yml"
      - ".github/workflows/docs.yml"
      - "pyproject.toml"
      - "harbor_cli/commands/**"

concurrency:
  group: docs-deploy

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Ensure latest pip
        run: python -m pip install --upgrade pip

      - name: Install ourself
        run: |
          pip install -e .

      - name: Install hatch
        run: pip install hatch

      - name: Generate CLI output data for mkdocs
        run: hatch run docs:python docs/scripts/gen_cli_data.py

      - name: Generate list of output formats
        run: hatch run docs:python docs/scripts/gen_formats.py

      - name: Generate list of CLI commands
        run: hatch run docs:python docs/scripts/gen_command_list_full.py

      - name: Build documentation and publish
        run: hatch run docs:mkdocs gh-deploy --force
